# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NA-TiGbaL1bD1Z21XXWFWVdeeJPZ5ilm
"""

import pandas as pd

data = pd.read_csv("Sales_Data.csv")
data

data.head(10)

data.isnull()

data.rename(columns={"Order Date":"datetime"})

x={"1":"January","2":"February","3":"March","4":"April","5":"May","6":"June","7":"July","8":"August","9":"September","10":"October","11":"November","12":"December"}

df["Month"] = df["Month"].map(x)

df

data.drop("Hour",axis=1,inplace=True)
data

agg = df.groupby("Product").agg({"Sales":"sum"})
print(agg)

data.sort_values(by="Month",ascending=False,inplace=True)

data

data

data.sort_values(by="Sales",ascending=False).head(5)

change=df.pivot_table(values=["Product","Sales"],index="Month",aggfunc="sum")

print(change)

df["Order Date"]= pd.to_datetime(df["Order Date"]).dt.date
grouped = df.groupby("Order Date")
sales=data.sort_values(by="Order Date",ascending=False).head()
sales

group=df.groupby("Product")['Quantity Ordered']
data.sort_values(by="Product",ascending=False).head(5)

import matplotlib.pyplot as plt

data.pivot_table(values='Sales',index='Product',aggfunc='sum').plot(kind='bar')
plt.tight_layout()
plt.show()

df['City_Codes']=df['City'].map({'Atlanta':'ATL','Austin':'AU','Boston':'BO','Dallas':'DA','Los Angeles':'LA','New York City':'NY','Portland':'PORT','San Francisco':'SF','Seattle':'SA'})
df


df[‘Order Date’]=pd.to_datetime(df[‘Ordered Date’])
df.groupby(“City”)
df.resample(‘6M’).agg(“Sales”:”sum”)




